# docker-compose.yml

version: '3'
services:
  server:
    image: postgrest/postgrest:v9.0.0.20220211
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
    networks:
      - gotapinetwork

  db:
    build: 
      context: .
      dockerfile: Dockerfile
    image: untdf-tnt2022-gotapidb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - gotapidb:/var/lib/postgresql/data
    networks:
      - gotapinetwork

  adminer:
    image: 'adminer:standalone'
    ports:
        - '8080:8080'
    networks:
        - gotapinetwork

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8181:8080"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - gotapinetwork

volumes:
  gotapidb: 
    driver: local

networks:
  gotapinetwork:
    driver: bridge